services:
  - type: web
    name: flask-image-enhancer
    env: python
    plan: starter  # change to free if you want (not recommended for RealESRGAN)
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 1 --threads 1 --timeout 120
    autoDeploy: true
