services:
  - type: web
    name: image-upscaler
    env: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    healthCheckPath: /health  
    envVars:
      - key: PORT
        value: 10000